services:
  invoices-pg:
    image: bitnami/postgresql:latest
    ports:
      - "5483:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=invoices
    volumes:
      - db_invoices:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d

volumes:
  db_invoices: